# Generated by Django 4.2.15 on 2024-08-21 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerateUniqueTrackingNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("origin_country_id", models.CharField(max_length=2)),
                ("destination_country_id", models.CharField(max_length=2)),
                ("weight", models.DecimalField(decimal_places=3, max_digits=6)),
                ("customer_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_slug", models.SlugField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tracking_number"],
                        name="unique_trac_trackin_0622c9_idx",
                    )
                ],
            },
        ),
    ]
